# Generated by Django 4.1.6 on 2024-08-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='photo_questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video'), ('photo', 'Photo')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video_questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.IntegerField(blank=True, choices=[(1, '#1'), (2, '#2'), (3, '#3'), (4, '#4')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
