# Generated by Django 4.1.6 on 2023-02-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer1",
            field=models.CharField(default="one", max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="answer2",
            field=models.CharField(default="two", max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="answer3",
            field=models.CharField(default="three", max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="answer4",
            field=models.CharField(default="four", max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
