# Generated by Django 4.1.6 on 2023-02-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_question_answer1_question_answer2_question_answer3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(default="hey", max_length=2048),
            preserve_default=False,
        ),
    ]
