# Generated by Django 4.1.6 on 2023-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_game_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=1024),
        ),
    ]
