# Generated by Django 4.1.6 on 2023-02-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_questionanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="name"),
        ),
    ]
