# Generated by Django 4.1.6 on 2023-02-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_player_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="game",
        ),
        migrations.RemoveField(
            model_name="questionanswer",
            name="player",
        ),
        migrations.RemoveField(
            model_name="questionanswer",
            name="question",
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="Player",
        ),
        migrations.DeleteModel(
            name="QuestionAnswer",
        ),
    ]
