# Generated by Django 4.1.6 on 2023-02-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_game_player_questionanswer_game_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
