# Generated by Django 4.1.6 on 2023-02-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_player_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="last_login_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
